timeout: 0

/fuga
	protocol: limine
  	path: boot():/boot/fuga
#	MODULE_PATH=boot:///servers/pci
#	MODULE_CMDLINE=pci
#	MODULE_PATH=boot:///servers/nvme
#	MODULE_CMDLINE=nvme
#	MODULE_PATH=boot:///servers/nvme_irq
#	MODULE_CMDLINE=nvme_irq
#	MODULE_PATH=boot:///servers/init
#	MODULE_CMDLINE=init
	kaslr: yes
