src += files('bcache.c', 'capability.c',
    'futex.c',
    'debug.c',
    'elf.c',
    'events.c',
    'init.c',
    'irq.c',
    'message.c',
    'mutex.c',
    'notification.c',
    'object.c',
    'resource.c',
    'semaphore.c',
    'syscall.c',
    'timer.c',
    'wait.c')

subdir('scheduler')
subdir('memory')
